fix github action workflows

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,25 +13,32 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
           python-version: "3.12"
+
       - name: Install uv
         uses: astral-sh/setup-uv@v4
+
       - name: Install dependencies
         run: |
           uv sync
+
       - name: Lint and Typecheck
         run: |
           make checkall
+
       - name: Package
         run: make packagecheck
+
       - name: Cache build artifacts
         uses: actions/cache@v4
         with:
           path: dist
-          key: ${{ runner.os }}-3.12-${{ runner.architecture }}-${{ hashFiles('**/pyproject.toml') }}-${{ github.sha }}
+          key: ${{ runner.os }}-3.12-x64-${{ hashFiles('**/pyproject.toml') }}-${{ github.sha }}
+
       - name: Store the distribution packages
         uses: actions/upload-artifact@v4
         with:
@@ -39,7 +46,6 @@ jobs:
           path: dist/
 
   tag-version:
-    name: Tag Version
     runs-on: ubuntu-latest
     permissions:
       contents: write  # Grant write access to the repository
@@ -49,25 +55,46 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.12'
+
       - name: Install uv
         uses: astral-sh/setup-uv@v4
+
+      - name: Install dependencies
+        run: |
+          uv sync
+
+      - name: Get version from __init__.py
+        id: get_version
+        run: |
+          version=$(uv run python -c "from src.par_scrape import __version__; print(__version__)")
+          echo "Raw version output: $version"
+          echo "VERSION=$version" >> $GITHUB_ENV
+
+      - name: Check version
+        id: check_version
+        run: |
+          echo "Version in env: ${{ env.VERSION }}"
+          if [ -z "${{ env.VERSION }}" ]; then
+            echo "Error: VERSION is empty"
+            exit 1
+          fi     
+
       - name: Configure Git
         run: |
           git config --global user.name "${{ github.actor }}"
           git config --global user.email "${{ github.event.pusher.email }}"
-      - name: Get version from __init__.py
-        id: get_version
-        run: |
-          echo "VERSION=$(uv run python -c "from src.par_scrape import __version__; print(__version__)")" >> $GITHUB_ENV
-          echo "Version extracted: ${{ env.VERSION }}"
+
       - name: App VERSION
         run: echo "VERSION is ${{ env.VERSION }}"
+
       - name: Fetch all tags
         run: git fetch --tags
+
       - name: Check if tag exists
         id: check_tag
         run: |
@@ -77,6 +104,7 @@ jobs:
           else
             echo "TAG_EXISTS=true" >> $GITHUB_ENV
           fi
+
       - name: Delete existing tag locally and remotely
         if: env.TAG_EXISTS == 'true'
         env:
@@ -85,6 +113,7 @@ jobs:
         run: |
           git tag -d "v$VERSION"
           git push --delete origin "v$VERSION"
+
       - name: Create new tag
         env:
           VERSION: ${{ env.VERSION }}
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,15 +20,37 @@ jobs:
         with:
           python-version: '3.12'
 
+      - name: Install uv
+        uses: astral-sh/setup-uv@v4
+
+      - name: Install dependencies
+        run: |
+          uv sync
+
+      - name: Get version from __init__.py
+        id: get_version
+        run: |
+          version=$(uv run python -c "from src.par_scrape import __version__; print(__version__)")
+          echo "Raw version output: $version"
+          echo "VERSION=$version" >> $GITHUB_ENV
+
+      - name: Check version
+        id: check_version
+        run: |
+          echo "Version in env: ${{ env.VERSION }}"
+          if [ -z "${{ env.VERSION }}" ]; then
+            echo "Error: VERSION is empty"
+            exit 1
+          fi
+
       - name: Restore cached build artifacts
         uses: actions/cache@v4
         with:
           path: dist
-          key: ${{ runner.os }}-3.12-${{ runner.architecture }}-${{ hashFiles('**/pyproject.toml') }}-${{ github.sha }}
-
+          key: ${{ runner.os }}-3.12-x64-${{ hashFiles('**/pyproject.toml') }}-${{ github.sha }}
           restore-keys: |
-            ${{ runner.os }}-3.12-${{ runner.architecture }}-${{ hashFiles('**/pyproject.toml') }}-
-            ${{ runner.os }}-3.12-${{ runner.architecture }}-
+            ${{ runner.os }}-3.12-x64-${{ hashFiles('**/pyproject.toml') }}-
+            ${{ runner.os }}-3.12-x64-
 
       - name: Sign the dists with Sigstore
         uses: sigstore/gh-action-sigstore-python@v3.0.0
@@ -42,7 +64,7 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
         run: |
           gh release create \
-          '${{ github.ref_name }}' \
+          'release-v${{ env.VERSION }}' \
           --repo '${{ github.repository }}' \
           --generate-notes \
           --latest
@@ -52,7 +74,7 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
         run: |
           gh release upload \
-          '${{ github.ref_name }}' dist/** \
+          'release-v${{ env.VERSION }}' dist/** \
           --repo '${{ github.repository }}'
 
       - name: Discord notification
